//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEsting.WaterShedService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WaterShedService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doLogin", ReplyAction="http://tempuri.org/IService1/doLoginResponse")]
        BOM.User doLogin(BOM.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doLogin", ReplyAction="http://tempuri.org/IService1/doLoginResponse")]
        System.Threading.Tasks.Task<BOM.User> doLoginAsync(BOM.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doRegister", ReplyAction="http://tempuri.org/IService1/doRegisterResponse")]
        bool doRegister(BOM.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doRegister", ReplyAction="http://tempuri.org/IService1/doRegisterResponse")]
        System.Threading.Tasks.Task<bool> doRegisterAsync(BOM.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TEsting.WaterShedService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TEsting.WaterShedService.IService1>, TEsting.WaterShedService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BOM.User doLogin(BOM.User user) {
            return base.Channel.doLogin(user);
        }
        
        public System.Threading.Tasks.Task<BOM.User> doLoginAsync(BOM.User user) {
            return base.Channel.doLoginAsync(user);
        }
        
        public bool doRegister(BOM.User user) {
            return base.Channel.doRegister(user);
        }
        
        public System.Threading.Tasks.Task<bool> doRegisterAsync(BOM.User user) {
            return base.Channel.doRegisterAsync(user);
        }
    }
}
