//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class User
    {
        public int uid { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string email { get; set; }
        [Required]
        public string password { get; set; }
        [Compare("password")]
        [Required]
        public string ConfirmPassword { get; set; }
        [Required]
        public string pincode { get; set; }
        [Required]
        public string role { get; set; }
     

    }
}
