//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.watershed_policy = new HashSet<watershed_policy>();
        }
        [Display(Name="User Id.")]
        public int uid { get; set; }
        [Required(ErrorMessage ="Username Not entered")]
        [Display(Name = "User Name.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email address Not entered")]
        [EmailAddress(ErrorMessage = "Invalid Mail Id")]
        [Display(Name = "User Email.")]
        public string email { get; set; }
        [Required(ErrorMessage = "Password Not entered")]
        [Display(Name = "User Password.")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Compare("password")]
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password.")]
        public string ConfirmPassword { get; set; }
        [Required]
       
        public string pincode { get; set; }
        [Required]
        public string role { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<watershed_policy> watershed_policy { get; set; }
    }
}
