//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class watershed_policy
    {
        public int pid { get; set; }
        public int vd_id { get; set; }
        public int crop_id { get; set; }
        public double cultivated_area { get; set; }
        public string year { get; set; }
        public int uid { get; set; }
    
        public virtual User user { get; set; }
        public virtual watershed_crop watershed_crop { get; set; }
        public virtual watershed_village_data watershed_village_data { get; set; }
    }
}
