//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class watershed_taluka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public watershed_taluka()
        {
            this.watershed_taluka_data = new HashSet<watershed_taluka_data>();
            this.watershed_village = new HashSet<watershed_village>();
        }
        [Display(Name = "Taluka Id.")]
        public int tid { get; set; }
        [Display(Name = "City Id")]
        public int cid { get; set; }
        [Display(Name = "Area")]
        public double area { get; set; }
        [Display(Name = "Tehshil Name")]
        public string Name { get; set; }
    
        public virtual watershed_city watershed_city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<watershed_taluka_data> watershed_taluka_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<watershed_village> watershed_village { get; set; }
    }
}
