//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class watershed_village
    {
        public int vid { get; set; }
        public int tid { get; set; }
        public double Area { get; set; }
        public string Pincode { get; set; }
        public string Name { get; set; }
    
        public virtual watershed_taluka watershed_taluka { get; set; }
        public virtual watershed_village_data watershed_village_data { get; set; }
    }
}
