//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class watershed_taluka_data
    {
        public int tal_id { get; set; }
        public int population { get; set; }
        public double waterreq { get; set; }
        public double rainfall { get; set; }
        public double wateravail { get; set; }
        public double water_sarcacity { get; set; }
        public System.DateTime cycle_year { get; set; }
        public int td_id { get; set; }
    
        public virtual watershed_taluka watershed_taluka { get; set; }
    }
}
