//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class watershedEntities : DbContext
    {
        public watershedEntities()
            : base("name=watershedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users1 { get; set; }
        public virtual DbSet<watershed_city> watershed_city { get; set; }
        public virtual DbSet<watershed_city_data> watershed_city_data { get; set; }
        public virtual DbSet<watershed_crop> watershed_crop { get; set; }
        public virtual DbSet<watershed_policy> watershed_policy { get; set; }
        public virtual DbSet<watershed_state> watershed_state { get; set; }
        public virtual DbSet<watershed_taluka> watershed_taluka { get; set; }
        public virtual DbSet<watershed_taluka_data> watershed_taluka_data { get; set; }
        public virtual DbSet<watershed_village> watershed_village { get; set; }
        public virtual DbSet<watershed_village_data> watershed_village_data { get; set; }
    }
}
