//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class watershed_village_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public watershed_village_data()
        {
            this.watershed_policy = new HashSet<watershed_policy>();
        }
    
        public int village_id { get; set; }
        public int population { get; set; }
        public double waterreq { get; set; }
        public double rainfall { get; set; }
        public double wateravail { get; set; }
        public double water_sarcacity { get; set; }
        public System.DateTime cycle_year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<watershed_policy> watershed_policy { get; set; }
        public virtual watershed_village watershed_village { get; set; }
    }
}
